nmap <buffer> <localleader>r <Plug>(go-run)
nmap <buffer> <localleader>b <Plug>(go-build)
nmap <buffer> <localleader>t <Plug>(go-test)
nmap <buffer> <localleader>gd <Plug>(go-doc)
nmap <buffer> <localleader>gv <Plug>(go-doc-vertical)
nmap <buffer> <localleader>gi <Plug>(go-implements)
nmap <buffer> <localleader>i <Plug>(go-info)
